# Generated by Django 4.2 on 2023-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='help_text',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
