# Generated by Django 4.2 on 2023-05-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_itemcategory_help_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malfunctionreport',
            old_name='room_schema_id',
            new_name='room_schema',
        ),
        migrations.RenameField(
            model_name='malfunctionreportitem',
            old_name='malfunction_report_id',
            new_name='malfunction_report',
        ),
        migrations.RenameField(
            model_name='roomitem',
            old_name='room_schema_id',
            new_name='room_schema',
        ),
        migrations.AlterField(
            model_name='item',
            name='characteristics',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
