# Generated by Django 4.2 on 2023-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_rename_item_category_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='zIndex',
            field=models.IntegerField(default=1),
        ),
    ]
