# Generated by Django 4.2 on 2023-05-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_itemcategory_zindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='zIndex',
        ),
    ]
