# Generated by Django 4.2 on 2023-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_itemcategory_zindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomschema',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomschema',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
