# Generated by Django 4.2 on 2023-05-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0009_roomschema_length_roomschema_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.item'),
        ),
    ]
