# Generated by Django 4.2 on 2023-05-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0010_alter_roomitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunctionreport',
            name='name',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
