# Generated by Django 4.2 on 2023-05-13 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemas', '0011_malfunctionreport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunctionreport',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
