# Generated by Django 4.2 on 2023-05-13 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0012_alter_malfunctionreport_taken_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunctionreportitem',
            name='malfunction_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_elements', to='schemas.malfunctionreport'),
        ),
    ]
