# Generated by Django 4.2 on 2023-05-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0013_alter_malfunctionreportitem_malfunction_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malfunctionreport',
            options={'permissions': (('take_malfunctionreport', 'Can take malfunction report in work'),)},
        ),
    ]
