# Generated by Django 4.2 on 2023-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0015_alter_malfunctionreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunctionreportstatus',
            name='color',
            field=models.CharField(blank=True, default='primary', max_length=63, null=True),
        ),
    ]
