# Generated by Django 4.2 on 2023-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownmenu',
            name='group_id',
            field=models.IntegerField(default=1),
        ),
    ]
