# Generated by Django 4.2 on 2023-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dropdownmenu_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownmenu',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='navigationmenu',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=63, null=True),
        ),
    ]
