# Generated by Django 4.2 on 2023-05-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_dropdownmenu_group_id_alter_dropdownmenu_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownmenu',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='dropdownmenu',
            name='title',
            field=models.CharField(blank=True, default='', max_length=63, null=True),
        ),
    ]
