# Generated by Django 4.2 on 2023-05-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('menu', '0006_navigationmenu_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownmenu',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.permission'),
        ),
    ]
